// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parcial2_AP1Albert.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230321000037_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("ProductoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoDetalle");
                });

            modelBuilder.Entity("Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Existencia")
                        .HasColumnType("REAL");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorInventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("producto");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 200f,
                            Descripcion = "Mani",
                            Existencia = 10f,
                            Precio = 250f,
                            ValorInventario = 0f
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 150f,
                            Descripcion = "Pasas",
                            Existencia = 5f,
                            Precio = 100f,
                            ValorInventario = 0f
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 75f,
                            Descripcion = "Ciruelas",
                            Existencia = 10f,
                            Precio = 300f,
                            ValorInventario = 0f
                        });
                });

            modelBuilder.Entity("ProductoDetalle", b =>
                {
                    b.HasOne("Productos", null)
                        .WithMany("ProductoDetalle")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Productos", b =>
                {
                    b.Navigation("ProductoDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
